language: python
python:
- '3.5'
install:
- pip install -r requirements-dev.txt .
script:
- pytest
deploy:
  provider: pypi
  username: __token__
  password:
  distributions: sdist bdist_wheel
  skip_existing: true
dd:
  secure: MtAK8FUvi7EJbBj+bXc41F4r5V/HRd8lRSPg7UfofDbu3eu2cO78GbMhkMZYZKtWDv/OwAXZnYAIfJQ4HdWrjNOHK+kAIiXq7cqm0DGJ5DYOQORJ/+3al1QFXvzvxLRzxTjPTjBtl2SRUTxtj0X5UnedIao2qYNuSkS8AesLbv01fJLNoG2rU4kqVSXu0vMiRumBKCdOa17S2L1ohRMY+esORgH6xBLL1b1YyWkMkJnO1tu+ZpGkbqD/F5tTtQh3w/fSnsjxb1vX+12/OWfvAg9mDX5IMqblSfDVNJCm7PY/MQVCHguYIOoOLYpV/bvPM+9cTzk8iGlSc51euL8ciSyxDUbeTzyV5T3ygdqhrBmUR4i2SOz9giCdJrXOTaFQCwNEbwpmOC6mC6bPg12U4v2kyCYiMPWKYw+MQPDAK0P/9sL6sMgDcn63ggLAvPLTe1KC30xZUka/QJUp7YRK3SKWYfRxkCreHiy4Phi6rebMuk5RLfVUKh7WDxx8KGHs7BrVR4Pe3hqwmp1jIBvcCcZ0PZt1zPs7+VNJ921KpTa3+rVyWf3Am48kWmA+xlKiHK5Sc7ojb5YkEcl8XkOb/NhRyRK0s/iETSO7nzU2F8RCpFjLKdzRzlfXnVVxewaOsmeDDv1ld1GBB2qE8XeTiq1GWv57GjvDRiqtOR6Ztmk=
